#!/bin/bash
#
# Infrastructure Setup for Bedrock AI Data Enrichment
# Run this ONCE to create all AWS resources
#

set -e

echo "=================================================="
echo "Bedrock AI Data Enrichment - Infrastructure Setup"
echo "=================================================="
echo ""

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not installed"
    echo ""
    echo "Install Terraform:"
    echo "  macOS:   brew install terraform"
    echo "  Linux:   https://www.terraform.io/downloads"
    echo "  Windows: https://www.terraform.io/downloads"
    exit 1
fi

echo "✅ Terraform installed: $(terraform version | head -1)"
echo ""

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured"
    echo ""
    echo "Configure AWS credentials:"
    echo "  Run: aws configure"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "✅ AWS credentials configured"
echo "   Account: $ACCOUNT_ID"
echo ""

# Navigate to terraform directory
cd "$(dirname "$0")/terraform"

# Initialize Terraform
echo "Initializing Terraform..."
terraform init

echo ""
echo "=================================================="
echo "Ready to create AWS resources"
echo "=================================================="
echo ""
echo "This will create:"
echo "  - 3 S3 buckets (input, output, audit)"
echo "  - 1 DynamoDB table (processing state)"
echo "  - 1 IAM role (application permissions)"
echo ""
echo "Estimated cost: ~$5-10/month (depending on usage)"
echo ""

read -p "Proceed? (yes/no): " -r
echo ""

if [[ ! $REPLY =~ ^[Yy]es$ ]]; then
    echo "Setup cancelled"
    exit 0
fi

# Apply Terraform configuration
echo "Creating AWS resources..."
terraform apply -auto-approve

echo ""
echo "=================================================="
echo "✅ INFRASTRUCTURE SETUP COMPLETE"
echo "=================================================="
echo ""

# Get outputs
INPUT_BUCKET=$(terraform output -raw input_bucket_name)
OUTPUT_BUCKET=$(terraform output -raw output_bucket_name)
AUDIT_BUCKET=$(terraform output -raw audit_bucket_name)
DYNAMODB_TABLE=$(terraform output -raw dynamodb_table_name)
IAM_ROLE=$(terraform output -raw iam_role_arn)
AWS_REGION=$(terraform output -raw aws_region)

# Save to .env file
cd ../..
cat > .env << EOF
# AWS Infrastructure Configuration (Auto-generated by setup.sh)
# Generated: $(date)

# AWS Account
AWS_REGION=${AWS_REGION}
AWS_ACCOUNT_ID=${ACCOUNT_ID}

# S3 Buckets
S3_INPUT_BUCKET=${INPUT_BUCKET}
S3_OUTPUT_BUCKET=${OUTPUT_BUCKET}
S3_AUDIT_BUCKET=${AUDIT_BUCKET}

# DynamoDB
DYNAMODB_TABLE=${DYNAMODB_TABLE}

# IAM
IAM_ROLE_ARN=${IAM_ROLE}

# Storage Mode
STORAGE_MODE=aws

EOF

echo "✅ Configuration saved to .env"
echo ""
echo "Resources created:"
echo "  - Input Bucket:  s3://${INPUT_BUCKET}"
echo "  - Output Bucket: s3://${OUTPUT_BUCKET}"
echo "  - Audit Bucket:  s3://${AUDIT_BUCKET}"
echo "  - DynamoDB Table: ${DYNAMODB_TABLE}"
echo ""
echo "Next steps:"
echo "  1. Build application code (src/)"
echo "  2. Create reference data files (reference_data/)"
echo "  3. Test locally"
echo ""

